# Generated by Django 3.0.5 on 2020-05-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('thumb', models.CharField(max_length=100)),
                ('gender', models.IntegerField(default=1)),
                ('hobby', models.CharField(max_length=100)),
                ('pos', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
            ],
        ),
    ]
