# Generated by Django 3.0.5 on 2020-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='userinfo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
