# Generated by Django 3.0.5 on 2020-05-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200520_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.UserInfo'),
        ),
    ]
