# Generated by Django 3.0.5 on 2020-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.CharField(max_length=1024, null=True)),
                ('content2', models.CharField(max_length=1024, null=True)),
                ('content3', models.CharField(max_length=1024, null=True)),
                ('content4', models.CharField(max_length=1024, null=True)),
                ('content5', models.CharField(max_length=1024, null=True)),
                ('content6', models.CharField(max_length=1024, null=True)),
                ('content7', models.CharField(max_length=1024, null=True)),
                ('content8', models.CharField(max_length=1024, null=True)),
                ('content9', models.CharField(max_length=1024, null=True)),
                ('backimg', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
