# Generated by Django 3.0.5 on 2020-05-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Content'),
        ),
    ]
