# Generated by Django 3.0.6 on 2020-05-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articletype_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='content',
        ),
        migrations.RemoveField(
            model_name='content',
            name='backimg',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content5',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content6',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content7',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content8',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content9',
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('articleType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType')),
            ],
        ),
        migrations.CreateModel(
            name='BackImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Column')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='column',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='article.Column'),
        ),
    ]
