# Generated by Django 3.0.6 on 2020-05-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_column_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
