# Generated by Django 3.0.6 on 2020-05-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
