# Generated by Django 3.0.6 on 2020-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_content_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='template',
            field=models.IntegerField(default=1),
        ),
    ]
