# Generated by Django 3.0.6 on 2020-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_content_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='template',
        ),
        migrations.AddField(
            model_name='column',
            name='template',
            field=models.IntegerField(default=1),
        ),
    ]
