# Generated by Django 3.0.6 on 2020-05-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200525_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='isfluid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='column',
            name='istitle',
            field=models.IntegerField(default=1),
        ),
    ]
